@startuml
title Product Usage Rating & Bill Generation

package "TMFC001 Product Catalog Management" #white {
  class "FixCommunication Service\n:ProductOffering" as FixCommServiceOffering {
    12 euro/month
  }
  class "CommercialTax\n:TaxProductOfferPriceAlteration" as CommercialTaxOffer {
    Rate = 20%
  }
  class ":UsageProdOfferPriceCharge" as DataCharge {
    Data = 1 euro/MO
  }
  class ":UsageProdOfferPriceCharge" as EuropeVoiceCharge {
    Europe voice = 0,5/min
  }
  class ":UsageProdOfferPriceCharge" as NationalVoiceCharge {
    National voice = 0,1euro/min
  }
  FixCommServiceOffering --> DataCharge
  FixCommServiceOffering --> EuropeVoiceCharge
  FixCommServiceOffering --> NationalVoiceCharge
  DataCharge --> CommercialTaxOffer : "impacted by"
  EuropeVoiceCharge --> CommercialTaxOffer : "impated by"
  NationalVoiceCharge --> CommercialTaxOffer : "impacted by"

  class "FixCommunication\n:ProductSpec" as FixCommSpec {
    Phone Number = to be chosen
    barring
    Roaming
  }
  class "Data\n:ProductUsageSpec" as DataUsageSpec {
    Subscriber Number
    Data Usage Start Time
    Data Usage End Time
    Total Data Used
    Type of Service
    Status
  }
  class "International Voice\n:ProductUsageSpec" as IntlVoiceUsageSpec {
    OriginatingPhoneNumber
    DestinationPhoneNumber
    Date and Time of Start
    Date and Time of End
    Call Duration
    DestinationCountry
    Call Type
    Call Status
  }
  class "Voice National\n:ProductUsageSpec" as NationalVoiceUsageSpec {
    OriginatingPhoneNumber
    DestinationPhoneNumber
    Date and Time of Start
    Date and Time of End
    Call Duration
    Call Status
    Call Type
  }
  FixCommSpec --> DataUsageSpec : "assocsiated to"
  FixCommSpec --> IntlVoiceUsageSpec : "assocsiated to"
  FixCommSpec --> NationalVoiceUsageSpec : "assocsiated to"

  DataCharge ..> DataUsageSpec : concerns
  EuropeVoiceCharge ..> IntlVoiceUsageSpec : concerns
  NationalVoiceCharge ..> NationalVoiceUsageSpec : concerns
}

package "TMFC030-Bill Generation Mgt" #white {
  class "John October Bill\n:Customer Bill" as JohnOctoberBill
  class "BillFormat=pdf\n:PartyBillSpec/PartyBillFormat" as PartyBillFormat
  class "Billing period= 1st October-31October\n:PartyBillingCycle" as PartyBillingCycle
  class "billigDateShift=1\nbillingPeriod=Monthly\nchargeDateOffset=0\n:PartyBillingCycleSpecification" as PartyBillingCycleSpec

  JohnOctoberBill --> PartyBillFormat : describedby
  JohnOctoberBill --> PartyBillingCycle : describedby
  PartyBillingCycleSpec --> PartyBillingCycle : triggeredby
}

package "TMFC024-BillingAccount Mgt" #FFE8CC {
  class "John Billing Account\n:CustomerBillingAccount" as JohnBillingAccount
}

PartyBillingCycle --> JohnBillingAccount : "configured For"
JohnBillingAccount --> PartyBillFormat : Customerbillspecifiedby
JohnBillingAccount --> JohnOctoberBill : "created For"

package "TMFC005-Product Inventory" #FFE8CC {
  class "FixCommunication Service\n:ProductOfferingInstance" as FixCommServiceInstance {
    Status = Initialized
    startDate = 10th Sep 2023
  }
  class "Fix Communication\n:Product" as FixCommProduct {
    Phone Number = "+33 9xx xxx xxx"
    barring = N
    Roaming = N
  }
  FixCommServiceInstance --> FixCommProduct : "generated by"
}

package "TMFC040-Product Usage" #D6E4F0 {
  class "Data\n:ProductUsage" as DataProductUsage
  class "International Voice\n:ProductUsage" as IntlVoiceProductUsage {
    OriginatingPhoneNumber = "+33 9xx xxx xxx"
    DestinationPhoneNumber = "+44 7 xx xx xx xx"
    Date and Time of Start = 2023-09-11 14:30:00
    Date and Time of End = 2023-09-11 14:35:00
    Call Duration = 5 minutes
    DestinationCounty = United-Kingdom
    Call Type = Outgoing
    Call Status = Completed
  }
  class "Voice National\n:ProductUsage" as NationalVoiceProductUsage

  class "Data\n:UsageProdPriceCharge" as DataPriceCharge {
    Tariff = "€15.00"
  }
  class "International Voice\n:UsageProdPriceCharge" as IntlVoicePriceCharge {
    tariff = "€2.50"
  }
  class "Voice National\n:UsageProdPriceCharge" as NationalVoicePriceCharge {
    tariff = "€1.00"
  }

  DataProductUsage --> DataPriceCharge : "rated by"
  IntlVoiceProductUsage --> IntlVoicePriceCharge : "rated by"
  NationalVoiceProductUsage --> NationalVoicePriceCharge : "rated by"
}

FixCommProduct <.. DataProductUsage : "guided to"
FixCommProduct <.. IntlVoiceProductUsage : "guided to"
FixCommProduct <.. NationalVoiceProductUsage : "guided to"

DataProductUsage --> DataUsageSpec : "described by"
IntlVoiceProductUsage --> IntlVoiceUsageSpec : "described by"
NationalVoiceProductUsage --> NationalVoiceUsageSpec : "described by"

DataProductUsage ..> DataCharge : uses
IntlVoiceProductUsage ..> EuropeVoiceCharge : uses
NationalVoiceProductUsage ..> NationalVoiceCharge : uses

package "TMFC031 Bill Calculation" #E2F0D9 {
  class "Data\n:AppliedCustomerbillingProdUsageRate" as DataAppliedRate {
    Tariff = "€15.00"
  }
  class "International Voice\n:AppliedCustomerbillingProdUsageRate" as IntlVoiceAppliedRate {
    tariff = "€2.50"
  }
  class "Voice National\n:AppliedCustomerbillingProdUsageRate" as NationalVoiceAppliedRate {
    tariff = "€1.00"
  }
  class "Data\n:AppliedCustomerBillingTaxRate" as DataTaxRate {
    Tariff = "€3"
    AppliedTaxRate = 20%
  }
  class "International Voice\n:AppliedCustomerBillingTaxRate" as IntlVoiceTaxRate {
    tariff = "€0,5"
    AppliedTaxRate = 20%
  }
  class "Voice National\n:AppliedCustomerBillingTaxRate" as NationalVoiceTaxRate {
    tariff = "€0,2"
    AppliedTaxRate = 20%
  }

  DataTaxRate --> DataAppliedRate : "altered by"
  IntlVoiceTaxRate --> IntlVoiceAppliedRate : "altered by"
  NationalVoiceTaxRate --> NationalVoiceAppliedRate : "altered by"
}

DataPriceCharge ..> DataAppliedRate : "corresponds to"
IntlVoicePriceCharge ..> IntlVoiceAppliedRate : "corresponds to"
NationalVoicePriceCharge ..> NationalVoiceAppliedRate : "corresponds to"

DataAppliedRate ..> JohnOctoberBill : presents
IntlVoiceAppliedRate ..> JohnOctoberBill : presents
NationalVoiceAppliedRate ..> JohnOctoberBill : presents

package "TMFC015-Service Usage Mgt" #E5DCF0 {
  class "Data\n:ServiceUsage" as DataServiceUsage {
    Subscriber Number = "+33 9xx xxx xxx"
    Data Usage Start Time = 2023-09-11 10:00:00
    Data Usage End Time = 2023-09-11 10:15:00
    Total Data Used = 15 MB
    Type of Service = Mobile Data
    Status = Completed
  }
  class "International Voice\n:ServiceUsage" as IntlVoiceServiceUsage {
    OriginatingPhoneNumber = "+33 9xx xxx xxx"
    DestinationPhoneNumber = "+44 7 xx xx xx xx"
    Date and Time of Start = 2023-09-11 14:30:00
    Date and Time of End = 2023-09-11 14:35:00
    Call Duration = 5 minutes
    DestinationPhoneCountryCodeValue = "+44"
    OriginatingPhoneCountryCodeValue = "+33"
    Call Type = Outgoing
    Call Status = Completed
  }
  class "Voice National\n:ServiceUsage" as NationalVoiceServiceUsage {
    OriginatingPhoneNumber = "+33 9xx xxx xxx"
    DestinationPhoneNumber = "+33 966 xxx xxx"
    Date and Time of Start = 2023-09-11 15:00:00
    Date and Time of End = 2023-09-11 15:10:00
    Call Duration = 10 minutes
    Call Type = Outgoing
    Call Status = Completed
  }
}

DataServiceUsage ..> DataProductUsage : "guided to"
IntlVoiceServiceUsage ..> IntlVoiceProductUsage : "guided to"
NationalVoiceServiceUsage ..> NationalVoiceProductUsage : "guided to"

@enduml
