@startuml
allowmixing
title TMFC050 : Product Recommendation Management -- Events (API / Resource / Event)

object publishedEvents
object subscribedEvents

object TMF680 {
  id = TMF680
  name = Product Recommendation Management API
  resources = (see below)
}

object TMF701 {
  id = TMF701
  name = Process Flow Management API
  resources = (see below)
}

object TMF620 {
  id = TMF620
  name = Product Catalog Management API
  resources = (see below)
}

publishedEvents --> TMF680
publishedEvents --> TMF701
subscribedEvents --> TMF620

rectangle "queryProductRecommendationCreateEvent\nqueryProductRecommendationStateChangeEvent" as TMF680Events
rectangle "processFlowCreateEvent\nprocessFlowStateChangeEvent\nprocessFlowStateDeleteEvent\nprocessFlowStateAttributeValueChangeEvent\ntaskFlowCreateEvent\ntaskFlowStateChangeEvent\ntaskFlowDeleteEvent\ntaskFlowAttributeValueChangeEvent\ntaskFlowInformationRequiredEvent" as TMF701Events
rectangle "productSpecificationCreate\nproductSpecificationDeleteEvent\ncategoryCreateEvent\ncategoryDeleteEvent\nproductOfferingCreateEvent\nproductOfferingAttributeValueChangeEvent\nproductOfferingStateChangeEvent\nproductOfferingDeleteEvent\nproductOfferingPriceCreateEvent\nproductOfferingPriceAttributeValueChangeEvent\nproductOfferingPriceStateChangeEvent\nproductOfferingPriceDeleteEvent" as TMF620Events

TMF680 --> TMF680Events
TMF701 --> TMF701Events
TMF620 --> TMF620Events
@enduml
