"""Reads: knowledge/index/{use-cases,components,apis}.json -- build_index.py's
own generated output, not the raw frontmatter/*.meta.json a second time.
Writes: knowledge/index/ontology.ttl
Track: shared -- run any time after build_index.py to refresh the RDF/OWL
export of the same cross-reference graph every skill already reads as JSON.

tools/build_ontology.py -- emits one Turtle file that is simultaneously an OWL
ontology (TBox: 3 disjoint classes, their datatype properties, and a small
named-relationship vocabulary for the use-case<->component/API graph) and its
instance data (ABox: one individual per cached artefact), generated purely
from the existing JSON indexes.

This is a DERIVED, secondary export -- see spec/spec-ontology.md for the full
reasoning. No skill should need a SPARQL engine or an OWL reasoner to answer
"what does TMFS001 depend on" when the JSON index already answers it with one
file read; this file exists for whoever specifically wants an RDF/OWL view of
the same data (Protege, a graph tool, a linked-data experiment), not for the
skills in skills/.

Provenance on the use-case<->component edge (confirmed / frontmatter_only /
matrix_only -- components.json's own used_by, spec.md 5.4) is carried as two
named object sub-properties (:documentReferencesComponent,
:matrixCreditsComponent) rather than RDF reification, and both are asserted
directly rather than left for a reasoner to derive from rdfs:subPropertyOf --
this file is fully queryable with plain triple matching, no reasoner required
(spec-ontology.md 7's determinism concern applies here too: this script's own
output must stay reasoner-independent).

Must be idempotent (spec.md principle 7): run twice on unchanged index files,
byte-identical output. Rows are walked in the sorted order build_index.py
already wrote them in; every set is sorted before being emitted.

Usage:
    python build_ontology.py
"""
import json
import os

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..")
INDEX_DIR = os.path.join(REPO_ROOT, "knowledge", "index")
OUT_PATH = os.path.join(INDEX_DIR, "ontology.ttl")

ONTOLOGY_IRI = "urn:tmforum-sdlc:ontology"
NS = ONTOLOGY_IRI + "#"
ID_NS = "urn:tmforum-sdlc:id#"

TBOX = """\
<urn:tmforum-sdlc:ontology> a owl:Ontology ;
    rdfs:label "TM Forum ODA SDLC cross-reference ontology"@en ;
    rdfs:comment \"\"\"Derived RDF/OWL export of knowledge/index/{use-cases,components,apis}.json. Generated by tools/build_ontology.py -- do not hand-edit (knowledge/AGENTS.md rule 4). See spec/spec-ontology.md for the design rationale and its scope: this models the ID/cross-reference layer only, not the full content of every use case/component/API document.\"\"\"@en .

#################################################################
# Classes
#################################################################

:Artefact a owl:Class ;
    rdfs:label "Artefact"@en ;
    rdfs:comment "Anything in the corpus carrying the universal envelope (spec.md 5.0): a use case, an ODA component, or an Open API."@en .

:UseCase a owl:Class ;
    rdfs:subClassOf :Artefact ;
    rdfs:label "Use Case"@en ;
    rdfs:comment "A TMFSxxx standalone use case."@en ;
    owl:disjointWith :Component, :API .

:Component a owl:Class ;
    rdfs:subClassOf :Artefact ;
    rdfs:label "ODA Component"@en ;
    rdfs:comment "A TMFCxxx ODA Component."@en ;
    owl:disjointWith :UseCase, :API .

:API a owl:Class ;
    rdfs:subClassOf :Artefact ;
    rdfs:label "Open API"@en ;
    rdfs:comment "A TMFxxx Open API, at a specific cached version -- apis.json has one row per (id, version) pair, so one individual here is one version, not one API family. See :apiFamily."@en ;
    owl:disjointWith :UseCase, :Component .

#################################################################
# Datatype properties -- envelope (spec.md 5.0) + use-case extension fields
#################################################################

:id a owl:DatatypeProperty ; rdfs:domain :Artefact ; rdfs:range xsd:string ;
    rdfs:comment "The stable TMFSxxx/TMFCxxx/TMFxxx identifier -- also encoded in the individual's own IRI local name; repeated as a literal for query convenience."@en .

:version a owl:DatatypeProperty ; rdfs:domain :Artefact ; rdfs:range xsd:string .

:status a owl:DatatypeProperty ; rdfs:domain :Artefact ; rdfs:range xsd:string ;
    rdfs:comment "The envelope's one-line rollup status (spec.md 5.0) -- a use case also has the more granular :maturity/:approvalStatus/:releaseStatus below."@en .

:path a owl:DatatypeProperty ; rdfs:domain :Artefact ; rdfs:range xsd:string ;
    rdfs:comment "Repo-relative path to the artefact's own file under knowledge/."@en .

:apiFamily a owl:DatatypeProperty ; rdfs:domain :API ; rdfs:range xsd:string ;
    rdfs:comment "The bare TMFxxx id shared by every cached version of the same API -- :id alone doesn't group an API's versions together (each version is its own individual); :apiFamily does."@en .

:maturity a owl:DatatypeProperty ; rdfs:domain :UseCase ; rdfs:range xsd:string .
:approvalStatus a owl:DatatypeProperty ; rdfs:domain :UseCase ; rdfs:range xsd:string .
:releaseStatus a owl:DatatypeProperty ; rdfs:domain :UseCase ; rdfs:range xsd:string .

#################################################################
# Object properties -- the cross-reference graph
#################################################################

:dependsOnComponent a owl:ObjectProperty ; rdfs:domain :UseCase ; rdfs:range :Component ;
    rdfs:comment "This use case depends on this component, per EITHER source -- asserted whenever components.json's used_by carries any entry for this pair, regardless of source. Prefer the two sub-properties below when provenance matters, which per knowledge/index/matrix-discrepancies.md is most of the time (14 of 24 use cases disagree between sources in one direction or the other)."@en .

:documentReferencesComponent a owl:ObjectProperty ; rdfs:subPropertyOf :dependsOnComponent ;
    rdfs:domain :UseCase ; rdfs:range :Component ;
    rdfs:comment "The use case's own document (its References section) names this component. components.json used_by source 'confirmed' or 'frontmatter_only'."@en .

:matrixCreditsComponent a owl:ObjectProperty ; rdfs:subPropertyOf :dependsOnComponent ;
    rdfs:domain :UseCase ; rdfs:range :Component ;
    rdfs:comment "IG1228 chapter 2's own use-case/component matrix credits this use case with this component, independent of what the use case's own document says. components.json used_by source 'confirmed' or 'matrix_only'. Per matrix-discrepancies.md this is the MORE common of the two disagreement directions, not the rarer one."@en .

:componentUsedByUseCase a owl:ObjectProperty ; owl:inverseOf :dependsOnComponent ;
    rdfs:domain :Component ; rdfs:range :UseCase ;
    rdfs:comment "Materialized inverse of :dependsOnComponent -- asserted directly in this file, not left for a reasoner to derive, so the file is queryable with plain triple matching and no reasoner."@en .

:dependsOnAPI a owl:ObjectProperty ; rdfs:domain :UseCase ; rdfs:range :API ;
    rdfs:comment "This use case's own document names this API. apis.json has no independent matrix source to reconcile against (IG1228 ch.2 covers use-case/component pairs only) -- unlike :dependsOnComponent, there is no separate 'matrix credits' sub-property here, because there is no second source for an API."@en .

:apiUsedByUseCase a owl:ObjectProperty ; owl:inverseOf :dependsOnAPI ;
    rdfs:domain :API ; rdfs:range :UseCase ;
    rdfs:comment "Materialized inverse of :dependsOnAPI."@en .
"""


def load(name):
    with open(os.path.join(INDEX_DIR, name), encoding="utf-8") as f:
        return json.load(f)


def esc(value):
    return str(value).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')


def lit(value):
    return f'"""{esc(value)}"""'


def iri(local):
    return f"id:{local}"


def api_local(api_row):
    return f'{api_row["id"]}_{api_row["version"]}'


def build_component_edges(components):
    """use_case_id -> {'depends', 'document', 'matrix'} sets of component ids,
    inverted from components.json's own (already-reconciled) used_by -- the
    single source of truth for this edge, per spec/spec.md 5.4."""
    edges = {}
    for comp in components:
        for entry in comp["used_by"]:
            e = edges.setdefault(entry["use_case"], {"depends": set(), "document": set(), "matrix": set()})
            e["depends"].add(comp["id"])
            if entry["source"] in ("confirmed", "frontmatter_only"):
                e["document"].add(comp["id"])
            if entry["source"] in ("confirmed", "matrix_only"):
                e["matrix"].add(comp["id"])
    return edges


def build_api_edges(apis):
    """use_case_id -> sorted set of api individual local names."""
    edges = {}
    for api in apis:
        for uc in api["used_by"]:
            edges.setdefault(uc, set()).add(api_local(api))
    return edges


def emit_use_cases(lines, use_cases, component_edges, api_edges):
    lines.append("#################################################################")
    lines.append("# Use cases")
    lines.append("#################################################################\n")
    for uc in sorted(use_cases, key=lambda r: r["id"]):
        subj = iri(uc["id"])
        ce = component_edges.get(uc["id"], {"depends": set(), "document": set(), "matrix": set()})
        ae = sorted(api_edges.get(uc["id"], set()))
        triples = [
            f"a :UseCase",
            f":id {lit(uc['id'])}",
            f"rdfs:label {lit(uc['name'])}",
            f":version {lit(uc['version'])}",
            f":status {lit(uc['status'])}",
        ]
        if uc.get("maturity"):
            triples.append(f":maturity {lit(uc['maturity'])}")
        if uc.get("approval_status"):
            triples.append(f":approvalStatus {lit(uc['approval_status'])}")
        if uc.get("release_status"):
            triples.append(f":releaseStatus {lit(uc['release_status'])}")
        triples.append(f":path {lit(uc['path'])}")
        if ce["depends"]:
            triples.append(":dependsOnComponent " + ", ".join(iri(c) for c in sorted(ce["depends"])))
        if ce["document"]:
            triples.append(":documentReferencesComponent " + ", ".join(iri(c) for c in sorted(ce["document"])))
        if ce["matrix"]:
            triples.append(":matrixCreditsComponent " + ", ".join(iri(c) for c in sorted(ce["matrix"])))
        if ae:
            triples.append(":dependsOnAPI " + ", ".join(iri(a) for a in ae))
        lines.append(f"{subj} " + " ;\n    ".join(triples) + " .\n")


def emit_components(lines, components):
    lines.append("#################################################################")
    lines.append("# Components")
    lines.append("#################################################################\n")
    for comp in sorted(components, key=lambda r: r["id"]):
        subj = iri(comp["id"])
        triples = [
            "a :Component",
            f":id {lit(comp['id'])}",
            f"rdfs:label {lit(comp['name'])}",
            f":version {lit(comp['version'])}",
            f":status {lit(comp['status'])}",
        ]
        if comp.get("path"):
            triples.append(f":path {lit(comp['path'])}")
        users = sorted(entry["use_case"] for entry in comp["used_by"])
        if users:
            triples.append(":componentUsedByUseCase " + ", ".join(iri(u) for u in users))
        lines.append(f"{subj} " + " ;\n    ".join(triples) + " .\n")


def emit_apis(lines, apis):
    lines.append("#################################################################")
    lines.append("# APIs")
    lines.append("#################################################################\n")
    for api in sorted(apis, key=lambda r: (r["id"], r["version"])):
        subj = iri(api_local(api))
        triples = [
            "a :API",
            f":id {lit(api['id'])}",
            f":apiFamily {lit(api['id'])}",
            f"rdfs:label {lit(api['name'])}",
            f":version {lit(api['version'])}",
            f":status {lit(api['status'])}",
        ]
        if api.get("path"):
            triples.append(f":path {lit(api['path'])}")
        users = sorted(api["used_by"])
        if users:
            triples.append(":apiUsedByUseCase " + ", ".join(iri(u) for u in users))
        lines.append(f"{subj} " + " ;\n    ".join(triples) + " .\n")


def main():
    use_cases = load("use-cases.json")
    components = load("components.json")
    apis = load("apis.json")

    component_edges = build_component_edges(components)
    api_edges = build_api_edges(apis)

    lines = [
        "@prefix : <" + NS + "> .",
        "@prefix id: <" + ID_NS + "> .",
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
        TBOX,
    ]
    emit_use_cases(lines, use_cases, component_edges, api_edges)
    emit_components(lines, components)
    emit_apis(lines, apis)

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")

    print(f"ontology.ttl: {len(use_cases)} use cases, {len(components)} components, {len(apis)} api versions")


if __name__ == "__main__":
    main()
