@startuml
title Pattern for (Actor) Intent Management (In progress)

actor "Actor" as Actor

box "CSP"
participant "Engagement\nManagement" as EM
participant "Party Interaction Mgt\nTMFC023" as PIM
participant "Lead & Opportunity\nTMFC036" as LO
participant "XXX\nTMFCXXX" as XXX
end box

Actor -> EM : 1a Access to Engagement Management Solution\nBusiness Intent about SASE Solution
EM -> EM : 1b Translation (regardless language)
EM -> PIM : 2a TMF683 Party Interaction\nPOST Party Interaction\n(date, used channel, intent, ...)
PIM -> PIM : 2b Create Interaction
PIM -> PIM : 2c Manage Intent
note right
  To be detailed...
  (A) Intent is managed by Party Interaction Mgt
      through dedicated AOF ?
  (B) Intent is managed by Party Request Mgt (!New)
      with dedicated AOF topic proposed to AN
end note
PIM -> LO : 2d Manage SalesLead / SalesOpportunity (regarding context)
PIM -> XXX : 2e TMF701 Process Flow Management API\nor ad hoc API to TMFC002 POCV, TMFC??? Product Assurance Mgt, ...
note right
  At this stage, interaction is classified as
  "I Buy", "I complain", ... and traduced in ad hoc langage
end note

@enduml
