@startuml
title Framework Agreement definition between the CSP and its Customer (simplified draft)

actor "B2B\nCustomer" as Customer
participant "CSP\nIT System\n(Solution)" as CSP
participant "Supplier\nIT System\n(Solution)" as Supplier

== 1. Customer Intent Management / SalesLead ==

Customer -> CSP : 1.1 Customer Request regarding Business intent (Secured "Overlay" / Network...)
CSP -> CSP : 1.2 Customer Intent management

== 2. Product Offering proposition / SalesOpportunity ==

Customer -> CSP : 2.1 Customer Request for 300 Sites, next 5 years...
CSP -> CSP : 2.2 Identify NBO (Next Best Offer)\nNBO process (incl. ref to Suppliers's assets)
CSP -> Supplier : 2.3 Check Commercial / Technical Eligibility\n(if required cf TMFS026)
Supplier -> CSP : 2.4 Supplier is OK
CSP -> CSP : 2.5 Constitution of bespoke high level Solution (incl. bespoke Products if necessary)
CSP -> Customer : 2.5 High level Product Offering's proposition (incl. high level price estimation, ...)

== 3. Definition of the Framework Agreement / FrameworkAgreement ==

Customer -> CSP : 3.1 Conditions & Price negociation
CSP -> Supplier : 3.2 Information regarding Customer's Framework Agreement\nif required in CSP/Supplier Framework Agreement, see TMFS026
Supplier -> CSP : 3.3 Supplier is OK
CSP -> CSP : 3.4 Description of the Framework Agreement by the CSP
CSP -> Customer : 3.5 Framework Agreement proposition
Customer -> CSP : 3.6 Customer accept and validation Framework Agreement proposed by the CSP

@enduml
