@startuml
title object Figure A.15 - Illustration 02: ImplementationAgreement between CSP and Supplier

object "Greenfield International Business:\nOrganization" as GreenfieldOrg {
  isLegalEntity = true
}
object "Cloud Experts:\nOrganization" as CloudExpertsOrg {
  isLegalEntity = true
}

object "Greenfield IB:\nAgreementRole" as GreenfieldRole
object "Cloud Experts:\nAgreementRole" as CloudExpertsRole

object "Greenfield IB / Cloud Experts Framework Agreement:\nFrameworkAgreement" as FrameworkAgreement {
  validFor = From 2025/09/01 to 2028/08/31
}
object "Greenfield IB / Cloud Experts CE Cloud Hosting Term or Condition:\nAgreementTermOrCondition" as AgreementTermOrCondition
object "Greenfield IB / Cloud Experts Cloud Hosting Offer Item:\nFrameworkAgreementItem" as FrameworkAgreementItem {
  validFor = From 2025/09/01 to 2026/08/31
}

object "Greenfield IB Prices Alteration for Cloud Hosting:\nProdOfferPriceAlteration" as ProdOfferPriceAlteration
object "CE Cloud Hosting Offer:\nAtomicProductOfferingSpecification" as AtomicPOSpec
object "CE Cloud Hosting Offer Price Plan:\nProductOfferingPrice" as ProductOfferingPrice
object "CE Cloud Hosting Offer standard Term or Condition:\nProductOfferingTermOrCondition" as ProductOfferingTermOrCondition

object "Greenfield IB Purchase Implementation Agreement Spec:\nImplementationAgreementSpecification" as ImplementationAgreementSpec

object "Greenfield IB / Cloud Experts SASE Implementation Agreement n°1:\nImplementationAgreement" as ImplementationAgreement {
  validFor = From 2025/10/15 to 2026/01/14
}
object "Greenfield IB / Cloud Experts Implementation Agreement n°1 Cloud Hosting Offer Item:\nImplementationAgreementItem" as ImplementationAgreementItem

object "Greenfield IB Product Order BPPO1:\nBusinessPartnerProductOrder" as BusinessPartnerProductOrder
object "Greenfield IB Cloud Hosting Product Offering Order Item BPPOO1.1:\nBusinessPartnerProductOfferingOrderItem" as BusinessPartnerProductOfferingOrderItem

object "Greenfield IB Cloud Hosting Installed Offer:\nAtomicProductOfferingInstance" as AtomicPOInstance {
  validFor = From 2025/10/15
}
object "Greenfield IB Installed Tariff Plan:\nProductPrice" as InstalledProductPrice {
  validFor = From 2025/10/15
}

GreenfieldOrg --> GreenfieldRole : :/OrganisationPlays
CloudExpertsOrg --> CloudExpertsRole : :/OrganisationPlays

GreenfieldRole --> ImplementationAgreement : :AgreementInvolves
CloudExpertsRole --> ImplementationAgreement : :AgreementInvolves

ImplementationAgreement --> ImplementationAgreementSpec : :ImplementationAgreementDescribedBy
ImplementationAgreement --> FrameworkAgreement : :ImplementationAgreementCanReferTo
ImplementationAgreement --> BusinessPartnerProductOrder : :ImplementationAgreementRefersTo
ImplementationAgreement --> ImplementationAgreementItem : :/ImplementationAgreementConsistsOf

ImplementationAgreementItem --> FrameworkAgreementItem : :ImplementationAgreementItemCanReferTo
ImplementationAgreementItem --> BusinessPartnerProductOfferingOrderItem : :ImplementationAgreementItemRefersTo
ImplementationAgreementItem --> AtomicPOInstance : :ImplementationAgreementItemCanInvolve

BusinessPartnerProductOrder --> BusinessPartnerProductOfferingOrderItem : :BusinessPartnerProductOrderComprisedOf
BusinessPartnerProductOfferingOrderItem --> AtomicPOInstance : :BPProductOfferingOrderItemInvolvesProductOfferingInstance

AtomicPOInstance --> InstalledProductPrice : :ProductOfferingInstanceValuedByPrice
InstalledProductPrice --> ProductOfferingPrice : :ProductPriceRealizesOrSubstitutes

FrameworkAgreement --> AgreementTermOrCondition : :/FrameworkAgreementGovernedBy
FrameworkAgreement --> FrameworkAgreementItem : :/FrameworkAgreementConsistsOf
FrameworkAgreementItem --> AgreementTermOrCondition : :/FrameworkAgreementItemGovernedBy
FrameworkAgreementItem --> AtomicPOSpec : :FrameworkAgreementItemConcerns
FrameworkAgreementItem --> ProdOfferPriceAlteration : :FrameworkAgreementItemHoldsNegotiated

AtomicPOSpec --> AtomicPOInstance : :AtomicPOSpecDescribes
AtomicPOSpec --> ProductOfferingPrice : :ProductOfferingSpecificationValuedBy
AtomicPOSpec --> ProductOfferingTermOrCondition : :ProdOfferAgreementRequirementsRepresentedAs
ProductOfferingTermOrCondition --> AgreementTermOrCondition : :ProductTermAppearsAs
ProductOfferingPrice --> ProdOfferPriceAlteration : :ProdOfferPriceImpactedBy

@enduml
